import axios from 'axios'

const api = axios.create({ baseURL: '/api' })
const codexHelper = axios.create({
  baseURL: import.meta.env.VITE_CODEX_HELPER_URL || 'http://127.0.0.1:8765',
  timeout: 8000,
})

export const useApi = () => ({
  getDashboard: () => api.get('/dashboard'),
  getCurrentWeather: (params) => api.get('/weather/current', { params }),
  getAthleteProfile: () => api.get('/settings/athlete-profile'),
  updateAthleteProfile: (payload) => api.put('/settings/athlete-profile', payload),
  getModalityRestrictions: () => api.get('/settings/modality-restrictions'),
  updateModalityRestrictions: (payload) => api.put('/settings/modality-restrictions', payload),
  getWorkoutTemplateSettings: () => api.get('/settings/workout-templates'),
  updateWorkoutTemplateSettings: (payload) => api.put('/settings/workout-templates', payload),
  getPerformanceSettings: () => api.get('/settings/performance'),
  updatePerformanceSettings: (payload) => api.put('/settings/performance', payload),
  getPlanningStatus: () => api.get('/planning/status'),
  getWeeklyCoaching: (params) => api.get('/coaching/weekly', { params }),
  getCoachingHistory: (params) => api.get('/coaching/history', { params }),
  getTrainingLoad: (params) => api.get('/training-load', { params }),
  getGoals: (params) => api.get('/goals', { params }),
  draftGoal: (payload) => api.post('/goals/draft', payload),
  createGoal: (payload) => api.post('/goals', payload),
  getStrengthOverview: (params) => api.get('/strength/overview', { params }),
  getStrengthWorkoutTemplates: () => api.get('/strength/workouts/templates'),
  getStrengthExerciseSuggestions: (params) => api.get('/strength/workouts/exercise-suggestions', { params }),
  createStrengthWorkoutTemplate: (payload) => api.post('/strength/workouts/templates', payload),
  updateStrengthWorkoutTemplate: (templateId, payload) => api.put(`/strength/workouts/templates/${templateId}`, payload),
  deleteStrengthWorkoutTemplate: (templateId) => api.delete(`/strength/workouts/templates/${templateId}`),
  getStrengthWorkoutSessions: (params) => api.get('/strength/workouts/sessions', { params }),
  getActiveStrengthWorkoutSession: () => api.get('/strength/workouts/sessions/active'),
  startStrengthWorkoutSession: (payload) => api.post('/strength/workouts/sessions', payload),
  getStrengthWorkoutSession: (sessionId) => api.get(`/strength/workouts/sessions/${sessionId}`),
  addStrengthWorkoutExercise: (sessionId, payload) => api.post(`/strength/workouts/sessions/${sessionId}/exercises`, payload),
  completeStrengthWorkoutSet: (sessionId, setId, payload) => api.post(`/strength/workouts/sessions/${sessionId}/sets/${setId}/complete`, payload),
  setStrengthWorkoutPosition: (sessionId, payload) => api.post(`/strength/workouts/sessions/${sessionId}/position`, payload),
  finishStrengthWorkoutSession: (sessionId, payload = {}) => api.post(`/strength/workouts/sessions/${sessionId}/finish`, payload),
  abandonStrengthWorkoutSession: (sessionId) => api.post(`/strength/workouts/sessions/${sessionId}/abandon`),
  deleteStrengthWorkoutSession: (sessionId) => api.delete(`/strength/workouts/sessions/${sessionId}`),
  getStrengthActivityCandidates: (sessionId) => api.get(`/strength/workouts/sessions/${sessionId}/activity-candidates`),
  linkStrengthWorkoutActivity: (sessionId, payload) => api.put(`/strength/workouts/sessions/${sessionId}/activity`, payload),
  getActivities: (params) => api.get('/activities', { params }),
  getActivityDetail: (activityId) => api.get(`/activities/${activityId}`),
  analyzeActivity: (activityId, payload) => api.post(`/activities/${activityId}/analysis`, payload),
  getActivityAnalysisContext: (activityId) => api.get(`/activities/${activityId}/analysis/context`),
  updateActivityIntent: (activityId, payload) => api.post(`/activities/${activityId}/intent`, payload),
  linkActivityToPlan: (activityId, payload) => api.post(`/activities/${activityId}/link-plan`, payload),
  importFitbodCsv: (payload) => api.post('/fitbod/import', payload),
  getLatestFitbodImport: () => api.get('/fitbod/imports/latest'),
  linkFitbodSessionToActivity: (sessionId, payload) => api.post(`/fitbod/sessions/${sessionId}/link`, payload),
  rejectFitbodSession: (sessionId, payload) => api.post(`/fitbod/sessions/${sessionId}/reject`, payload),
  getActivityFeedback: (activityId) => api.get(`/activities/${activityId}/feedback`),
  saveActivityFeedback: (activityId, payload) => api.post(`/activities/${activityId}/feedback`, payload),
  getCalendarWeeks: (params) => api.get('/calendar/weeks', { params }),
  getCalendarMonth: (params) => api.get('/calendar/month', { params }),
  getWeeklyPlans: (params) => api.get('/plans/weekly', { params }),
  getWeeklyPlanTrends: (params) => api.get('/plans/weekly/trends', { params }),
  previewWeeklyPlanAdjustment: (payload) => api.post('/plans/weekly/adjust/preview', payload),
  adjustWeeklyPlan: (payload) => api.post('/plans/weekly/adjust', payload),
  startCodexWeeklyPlan: (payload) => codexHelper.post('/weekly-plan', payload),
  getCodexWeeklyPlanJob: (jobId) => codexHelper.get(`/weekly-plan/${encodeURIComponent(jobId)}`),
  startCodexWeeklyPlanRevision: (payload) => codexHelper.post('/weekly-plan-revision', payload),
  getCodexWeeklyPlanRevisionJob: (jobId) => codexHelper.get(`/weekly-plan-revision/${encodeURIComponent(jobId)}`),
  startCodexActivityAnalysis: (payload) => codexHelper.post('/activity-analysis', payload),
  getCodexActivityAnalysisJob: (jobId) => codexHelper.get(`/activity-analysis/${encodeURIComponent(jobId)}`),
  getStravaStatus: () => api.get('/integrations/strava/status'),
  importStravaActivities: (payload) => api.post('/integrations/strava/import', payload),
  backfillStravaStreams: (payload) => api.post('/integrations/strava/streams/backfill', payload),
  previewHealthFitImport: () => api.get('/integrations/healthfit/preview'),
  importHealthFitFiles: () => api.post('/integrations/healthfit/import'),
  previewHealthDataImport: () => api.get('/integrations/health-data/preview'),
  importHealthDataFiles: () => api.post('/integrations/health-data/import'),
  getNotes: (params) => api.get('/notes', { params }),
  getCoachChatConversations: () => api.get('/notes/chat/conversations'),
  createCoachChatConversation: (payload = {}) => api.post('/notes/chat/conversations', payload),
  deleteCoachChatConversation: (conversationId) => api.delete(`/notes/chat/conversations/${conversationId}`),
  getCoachChatMessages: (params) => api.get('/notes/chat', { params }),
  createCoachChatMessage: (payload) => api.post('/notes/chat', payload),
  startCodexCoachChat: (payload) => codexHelper.post('/coach-chat', payload),
  getCodexCoachChatJob: (jobId) => codexHelper.get(`/coach-chat/${encodeURIComponent(jobId)}`),
  getWeekly: () => api.get('/weekly'),
  getMetric: (name) => api.get(`/metrics/${name}`),
  getPerformanceSummary: () => api.get('/metrics/performance-summary'),
  getHealthSummary: (params) => api.get('/metrics/health-summary', { params }),
  getTrainingHistory: () => api.get('/metrics/training-history'),
  createMetric: (payload) => api.post('/metrics', payload),
})
